
package guia;

import javax.swing.JOptionPane;

/**
 *
 * @author  Mauricio Calderon && Melanie Estrada
 */

public class Guia1 extends javax.swing.JFrame {

    double vec[] = new double[10];
    public Guia1() {
        initComponents();
        this.setSize(410,330);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComBoxOpciones = new javax.swing.JComboBox<>();
        jLabelDimension1 = new javax.swing.JLabel();
        jLabelDimension2 = new javax.swing.JLabel();
        jTextFieldD1 = new javax.swing.JTextField();
        jTextFieldD2 = new javax.swing.JTextField();
        jButtonCalcular = new javax.swing.JButton();
        jLblResultado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Promedio y Calculos Geometricos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(112, 11, 157, 14);

        jComBoxOpciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Área de una figura de 4 lados", "Calcular circunferencia", "Volumen de una esfera", "Volumen de un cubo", "Promedio" }));
        jComBoxOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComBoxOpcionesActionPerformed(evt);
            }
        });
        getContentPane().add(jComBoxOpciones);
        jComBoxOpciones.setBounds(112, 43, 167, 44);

        jLabelDimension1.setForeground(new java.awt.Color(240, 240, 240));
        jLabelDimension1.setText("Dimension 1:");
        getContentPane().add(jLabelDimension1);
        jLabelDimension1.setBounds(46, 126, 80, 14);

        jLabelDimension2.setForeground(new java.awt.Color(240, 240, 240));
        jLabelDimension2.setText("Dimension 2:");
        getContentPane().add(jLabelDimension2);
        jLabelDimension2.setBounds(46, 194, 90, 14);
        getContentPane().add(jTextFieldD1);
        jTextFieldD1.setBounds(176, 123, 130, 20);
        getContentPane().add(jTextFieldD2);
        jTextFieldD2.setBounds(176, 188, 130, 20);

        jButtonCalcular.setText("Calcular");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCalcular);
        jButtonCalcular.setBounds(46, 253, 110, 23);
        getContentPane().add(jLblResultado);
        jLblResultado.setBounds(158, 253, 148, 23);

        jLabel2.setBackground(new java.awt.Color(0, 204, 153));
        jLabel2.setForeground(new java.awt.Color(0, 255, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guia/imagen6.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComBoxOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComBoxOpcionesActionPerformed
        String opcion = jComBoxOpciones.getSelectedItem().toString();

        switch(opcion){
            case "Área de una figura de 4 lados" :

            break;

            case "Calcular circunferencia" :

                jLabelDimension1.setText("Radio: ");
                jTextFieldD2.setVisible(false);
                jLabelDimension2.setText("");
            break;

            case "Volumen de una esfera":
                jLabelDimension1.setText("Radio: ");
                jTextFieldD2.setVisible(false);
                jLabelDimension2.setText("");
            break;

            case "Volumen de un cubo":
            jLabelDimension1.setText("Arista: ");
            jTextFieldD2.setVisible(false);
            jLabelDimension2.setText("");
            break;

            case "Promedio" :
            jLabelDimension1.setText("");
            jLabelDimension2.setText("");
            jTextFieldD1.setVisible(false);
            jTextFieldD2.setVisible(false);
            for(int j=0;j<vec.length;j++){
                vec[j]=Double.parseDouble(JOptionPane.showInputDialog("Ingrese la nota "+(j+1)));
            }
            jLblResultado.setText("Datos ingresados, presione calcular");

        }

    }//GEN-LAST:event_jComBoxOpcionesActionPerformed

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        String opcion = jComBoxOpciones.getSelectedItem().toString();
        double area,arista,diagonal,radio;
       switch(opcion){
           
             case "Área de una figura de 4 lados" : 
                 double var1,var2;
                        var1 = Double.parseDouble(jTextFieldD1.getText());
                        var2=Double.parseDouble(jTextFieldD2.getText());
                        area=var1*var2;
                        diagonal=(1.4142)*(var1); 
                    jLblResultado.setText("El area es: "+area+ "\n La diagonal es: "+diagonal);


                    break;
       
       case "Calcular circunferencia" : 
           
                 radio=Double.parseDouble(jTextFieldD1.getText());
                    area=3.1416*(radio*radio);
                 jLblResultado.setText("El area es: "+area); 
                break;
                
       case "Volumen de una esfera":
                
                    radio=Double.parseDouble(jTextFieldD1.getText());
                    area=(1.333)*(3.1416)*(radio)*(radio)*(radio);
                jLblResultado.setText("El volumen es: "+area); 
              break;
                
       case "Volumen de un cubo":
           arista=Double.parseDouble(jTextFieldD1.getText());
           area=(arista*arista*arista);
            jLblResultado.setText("El volumen es: "+area);
          break;
          
       case "Promedio":
           
           double sum=0, prom;
           
           for(int j=0;j<vec.length;j++){
          sum=sum+vec[j];
          prom=sum/vec.length;
          jLblResultado.setText("El Promedio es: "+prom);
          }
  }
    }                                        

                                   

    private void jComboBoxOpcionesActionPerformed2(java.awt.event.ActionEvent evt) {                                        
        
        
        
    }//GEN-LAST:event_jButtonCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Guia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Guia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Guia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Guia1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JComboBox<String> jComBoxOpciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDimension1;
    private javax.swing.JLabel jLabelDimension2;
    private javax.swing.JLabel jLblResultado;
    private javax.swing.JTextField jTextFieldD1;
    private javax.swing.JTextField jTextFieldD2;
    // End of variables declaration//GEN-END:variables
}
