/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guia;

import javax.swing.JOptionPane;

/**
 *
 * @author  Mauricio Calderon && Melanie Estrada
 */
public class Guia2 extends javax.swing.JFrame {

    /**
     * Creates new form Guia2
     */
    public Guia2() {
        initComponents();
        this.setSize(460, 221);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelOpciones = new javax.swing.JLabel();
        jButtonIngresar = new javax.swing.JButton();
        jButtonOrdenar = new javax.swing.JButton();
        jButtonVer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelTitulo.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(240, 240, 240));
        jLabelTitulo.setText("Ordenamiento de Letras");
        getContentPane().add(jLabelTitulo);
        jLabelTitulo.setBounds(135, 11, 230, 21);

        jLabelOpciones.setForeground(new java.awt.Color(240, 240, 240));
        jLabelOpciones.setText("Opciones:");
        getContentPane().add(jLabelOpciones);
        jLabelOpciones.setBounds(27, 43, 57, 14);

        jButtonIngresar.setText("Ingresar datos");
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIngresar);
        jButtonIngresar.setBounds(27, 63, 115, 23);

        jButtonOrdenar.setText("Ordenar datos");
        jButtonOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOrdenar);
        jButtonOrdenar.setBounds(160, 63, 141, 23);

        jButtonVer.setText("Ver datos");
        jButtonVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVer);
        jButtonVer.setBounds(328, 63, 118, 23);

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane1.setViewportView(jTextArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(19, 104, 417, 74);

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guia/fondo4.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo);
        jLabelFondo.setBounds(0, 0, 460, 230);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed
        String entrada="";
        for (int i = 0; i < 10; i++) {
            entrada = JOptionPane.showInputDialog("Ingrese la letra " + i + "/10");
            validacion c = new validacion();
            if (c.validar(entrada.toUpperCase()) == true) {
                letras[i] = entrada;
            } else {
                JOptionPane.showMessageDialog(null, "No es una letra");
                i = i - 1;
            }
     
        }
        jTextArea.setText("Presione Ver datos para ver datos tal y como se ingresaron\nPresione Ordenar datos y luego Ver datos para verlos ordenados ");
    }//GEN-LAST:event_jButtonIngresarActionPerformed

    private void jButtonOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarActionPerformed
        String aux;
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 9; j++) {
                if (letras[j].compareToIgnoreCase(letras[j + 1]) > 0) {
                    aux = letras[j + 1];
                    letras[j + 1] = letras[j];
                    letras[j] = aux;

                }
            }

        }
        jTextArea.setText("Presione Ver datos para ver datos ordenados");
    }//GEN-LAST:event_jButtonOrdenarActionPerformed

    private void jButtonVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerActionPerformed
         jTextArea.setText("");
        String cadena="";
        for (int i = 0; i < 10; i++) {
            cadena+=letras[i] + " ";
        }
        jTextArea.setText(cadena);
    }//GEN-LAST:event_jButtonVerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Guia2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Guia2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Guia2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guia2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Guia2().setVisible(true);
            }
        });
    }
     String letras[]= new String [10];

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JButton jButtonOrdenar;
    private javax.swing.JButton jButtonVer;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelOpciones;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea;
    // End of variables declaration//GEN-END:variables
}

