/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guia;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author mauca
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setSize(475, 350);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jLabelTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldUsr = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jButtonLog = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelTitulo.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("LOGIN");
        getContentPane().add(jLabelTitulo);
        jLabelTitulo.setBounds(180, 50, 80, 29);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Contraseña:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 180, 90, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 130, 80, 17);

        jTextFieldUsr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldUsrKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldUsrKeyReleased(evt);
            }
        });
        getContentPane().add(jTextFieldUsr);
        jTextFieldUsr.setBounds(150, 130, 190, 30);

        jPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordKeyReleased(evt);
            }
        });
        getContentPane().add(jPassword);
        jPassword.setBounds(150, 180, 190, 30);

        jButtonLog.setText("Ingresar");
        jButtonLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLog);
        jButtonLog.setBounds(190, 240, 100, 23);

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guia/login.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo);
        jLabelFondo.setBounds(0, 0, 460, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUsrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUsrKeyReleased
        char input=evt.getKeyChar();
        if (Character.isLetter(input) ) {
            String cadena=jTextFieldUsr.getText().toUpperCase();
            jTextFieldUsr.setText(cadena);
            
        }
    }//GEN-LAST:event_jTextFieldUsrKeyReleased

    private void jPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordKeyReleased
        char input=evt.getKeyChar();
        if (Character.isLetter(input) ) {
            String cadena=new String(jPassword.getPassword());
            cadena=cadena.toUpperCase();
            jPassword.setText(cadena);
            
        }
    }//GEN-LAST:event_jPasswordKeyReleased

    private void jButtonLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogActionPerformed
        String pass= "123ABC";
        String usr="ADMIN";
        Menu menu= new Menu();
        String contra= new String(jPassword.getPassword());
        if (jTextFieldUsr.getText().equals(usr) && contra.equals(pass)) {
            JOptionPane.showMessageDialog(null,"Entraste");
            this.setVisible(false);
            menu.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null,"Usuario o contraseña incorrectos");
            jPassword.setText("");
        }
    }//GEN-LAST:event_jButtonLogActionPerformed

    private void jTextFieldUsrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUsrKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER && jTextFieldUsr.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Necesita llenar el campo");
        } else if (evt.getKeyCode()==KeyEvent.VK_ENTER && jTextFieldUsr.getText().isEmpty()==false){
            jTextFieldUsr.transferFocus();
        }
    }//GEN-LAST:event_jTextFieldUsrKeyPressed

    private void jPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordKeyPressed
        String contra= new String(jPassword.getPassword());
        if (evt.getKeyCode()==KeyEvent.VK_ENTER && contra.equals("")){
            JOptionPane.showMessageDialog(null, "Necesita llenar el campo");
        } else if (evt.getKeyCode()==KeyEvent.VK_ENTER && contra.isEmpty()==false ){
            jPassword.transferFocus();
        }
    }//GEN-LAST:event_jPasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JTextField jTextFieldUsr;
    // End of variables declaration//GEN-END:variables
}
